rm -rf logs/*
echo Removed log files.....
sleep 2
make clean all clobber
sleep 2
echo Generated build file.........
./ooosim 8 64 gcc_trace.txt > logs/gcc_run.log
sleep 3s
echo GCC Run Completed..........
./ooosim 3 16 perl_trace.txt > logs/perl_run.log
sleep 2s
echo PERL Run Completed............
echo Comparing GCC Run........
diff -iw outputs/gcc_val.txt logs/gcc_run.log > logs/diff_gcc.log
sleep 2s
echo Comparing PERL Run........
diff -iw outputs/perl_val.txt logs/perl_run.log > logs/diff_perl.log
echo Simulation Done!!!!!!!